config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :budgetplaners
  resources :wallets
  
  resources :travels
  post '/home/index' , to:'users#create'
  root 'home#index'
  
  get '/register', to: 'users#new'
  
  resources :users, only: [:create]
  get '/sign_in', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'
  get '/user', to: 'users#show'
  get '/user/index', to: 'users#index'
  get '/delete/:id', to: 'users#delete'
  resources :sessions, only:[:create]
 
  
  
  


  
end

app/models/user.rb
class User < ApplicationRecord
    validates :email,uniqueness:true
    validates :email, presence:true
    validates :password, length:{minimum: 4,allow_nil: true}
    has_many:travel
    has_many:budgetplaner
    has_many:wallet
    has_many:category
    def password
        @password
    end
    def password=(raw)
        @password=raw
        self.password_digest=BCrypt::Password.create(raw)
    end
    def is_password?(raw)
        BCrypt::Password.new(password_digest).is_password?(raw)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all 

    
  end
  def show
    @user=current_user
   
    
  end
  def new
    @user=User.new
  end
  def create
    @user= User.new(user_params)
    if @user.save
      flash.now[:notice]="Sucessfully Registered"
      redirect_to user_path
    else
      flash.now[:notice]=@user.errors.full_messages.to_sentence
      render :new
    end


  end
  def delete
    @user=User.find(params[:id])
    @wallets=@user.wallet.all
    for w in @wallets
      w.destroy
    end
    @bs=@user.budgetplaner.all
    for b in @bs 
      b.destroy
    end
    @user.destroy
    @users=User.all;
    redirect_to user_index_path
    
  end
  private 
  def user_params
    params.require(:user).permit(:email, :password, :is_admin)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
    <div>
    <%= form.label :Email, style: "display: block" %>
    <%= form.email_field :email %>
    </div>
    <div>
    <%= form.label :Password, style: "display: block" %>
    <%= form.password_field :password %>
    </div>    
    <div>
    <%= form.submit %>
    </div>
<%end%>

app/views/users/edit.html.erb
<form action="" method ="post">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">
    <label for="email">Email</label>
    <input type="email" id="email" name="user[email]" value="<%=@user.email%>"/>
    <label for="password">Password</label>
    <input type="password" id="password" name="user[password]" />
    
    <input type="submit" value="Register">

</form>

app/views/users/index.html.erb
<h1>All the users are </h1>
<% @users.each do |t| %>
    <%=t.email%> <br>
   <a href="/delete/<%=t.id%>" method="delete" >Delete</a><br>

<%end%>


<%= link_to "Register", register_path%>
<%= link_to "Admin HomePage", user_path %>

app/views/users/new.html.erb
<p id="notice"><%=notice%></p>
<h1>Registration form</h1>

<%= render "form", user: @user %>

<%= link_to "Admin HomePage", user_path %>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>
<h1>You are logged in as <%=current_user.email%></h1>


<div>
  
  
  <%=link_to "Category",categories_path %><br>
  <%= link_to "Wallets", wallets_path %><br>
  <%= link_to "Budget Planner", budgetplaners_path %><br>
  <%=link_to "Sign out", sign_out_path %><br>
  <%if current_user.is_admin==true %>
  <%= link_to "Add New User", register_path%><br>
  <%=link_to "All User List",user_index_path %>
  <%end%>
</div>