config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :budgetplaners
  resources :wallets
  
  resources :travels
  post '/home/index' , to:'users#create'
  root 'home#index'
  
  get '/register', to: 'users#new'
  
  resources :users, only: [:create]
  get '/sign_in', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'
  get '/user', to: 'users#show'
  get '/user/index', to: 'users#index'
  get '/delete/:id', to: 'users#delete'
  resources :sessions, only:[:create]
 
  
  
  


  
end

app/models/wallet.rb
class Wallet < ApplicationRecord
    belongs_to:user
    
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :set_wallet, only: %i[ show edit update destroy ]

  
  def index
    @user=current_user
    if @user.is_admin==true
      
      @wallets=Wallet.all
    else
      @wallets = @user.wallet.all
    end
  end

  
  def show
  end

  
  def new
    @wallet = Wallet.new
  end

 
  def edit
  end
  

  
  def create
    @wallet = Wallet.new(wallet_params)

    respond_to do |format|
      if @wallet.save
        format.html { redirect_to wallet_url(@wallet), notice: "Wallet was successfully created." }
        
      else
        format.html { render :new, status: :unprocessable_entity }
        
      end
    end
  end

  
  def update
    respond_to do |format|
      if @wallet.update(wallet_params)
        format.html { redirect_to wallet_url(@wallet), notice: "Wallet was successfully updated." }
        
      else
        format.html { render :edit, status: :unprocessable_entity }
        
      end
    end
  end

  
  def destroy
    @wallet.destroy

    respond_to do |format|
      format.html { redirect_to wallets_url, notice: "Wallet was successfully destroyed." }
      
    end
  end

  private
    
    def set_wallet

      @wallet = Wallet.find(params[:id])
    end

    
    def wallet_params
      params.require(:wallet).permit(:amount, :month,:user_id)
    end
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/_form.html.erb
<%= form_with(model: wallet) do |form| %>
  <% if wallet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
        <% wallet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :month, style: "display: block" %>
    <%= form.text_field :month %>
  </div>
  <div>
  <%if current_user.is_admin==true%>
    <%= form.number_field :user_id%>     
    
  <%else%>
    <%= form.number_field :user_id ,value: current_user.id, type: :hidden%>
      
  <% end %>  
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wallets/_wallet.html.erb
<div id="<%= dom_id wallet %>">
  <p>
    <strong>Amount:</strong>
    <%= wallet.amount %>
  </p>

  <p>
    <strong>Month:</strong>
    <%= wallet.month %>
  </p>
  <p>
    <strong>id:</strong>
    <%= wallet.user_id %>
  </p>

</div>

app/views/wallets/edit.html.erb
<h1>Editing wallet</h1>

<%= render "form", wallet: @wallet %>

<br>

<div>
  <%= link_to "Show this wallet", @wallet %> |
  <%= link_to "Back to wallets", wallets_path %>
</div>

app/views/wallets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wallets</h1>

<div id="wallets">
  
   <% @wallets.each do |wallet| %>
      <%= render wallet %>
      <p>
      <%= link_to "Show this wallet", wallet %>
      </p>
    <%end%>
    
  
    
  

</div>

<%= link_to "New wallet", new_wallet_path %>
<%= link_to "User HomePage", user_path %>

app/views/wallets/new.html.erb
<h1>New wallet</h1>

<%= render "form", wallet: @wallet %>

<br>

<div>
  <%= link_to "Back to wallets", wallets_path %>
</div>

app/views/wallets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wallet %>

<div>
  <%= link_to "Edit this wallet", edit_wallet_path(@wallet) %> |
  <%= link_to "Back to wallets", wallets_path %>

  <%= button_to "Destroy this wallet", @wallet, method: :delete %>
</div>