config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :budgetplaners
  resources :wallets
  
  resources :travels
  post '/home/index' , to:'users#create'
  root 'home#index'
  
  get '/register', to: 'users#new'
  
  resources :users, only: [:create]
  get '/sign_in', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'
  get '/user', to: 'users#show'
  get '/user/index', to: 'users#index'
  get '/delete/:id', to: 'users#delete'
  resources :sessions, only:[:create]
 
  
  
  


  
end

app/models/budgetplaner.rb
class Budgetplaner < ApplicationRecord
    belongs_to:user
    has_many:category
end

app/controllers/budgetplaners_controller.rb
class BudgetplanersController < ApplicationController
  before_action :set_budgetplaner, only: %i[ show edit update destroy ]

  # GET /budgetplaners or /budgetplaners.json
  def index
    @user=current_user
    if @user.is_admin==true
      @budgetplaners = Budgetplaner.all
    else
      @budgetplaners= @user.budgetplaner.all
    end

  end

  # GET /budgetplaners/1 or /budgetplaners/1.json
  def show
  end

  # GET /budgetplaners/new
  def new
    @budgetplaner = Budgetplaner.new
  end

  # GET /budgetplaners/1/edit
  def edit
  end

  # POST /budgetplaners or /budgetplaners.json
  def create
    @budgetplaner = Budgetplaner.new(budgetplaner_params)
    #categories_list=Category.all
    #@categories=nil
    #list=nil
    #for c in categories_list

      #list.append(c.cgory)
      #puts(list)
    #end
    @cat=Category.all
    
    respond_to do |format|
      if  balance_sufficient(@budgetplaner) && @budgetplaner.save
        format.html { redirect_to budgetplaner_url(@budgetplaner), notice: "Budgetplaner was successfully created." }
        
      else
        flash.notice="Insuffiient wallet balance for this month"
       
        format.html {  render :new, status: :unprocessable_entity  }
        
      end
    end
  end
  def balance_sufficient(bplaner)
    @budgetplaner=bplaner
    flag=false
    @user=current_user
    if @user.is_admin==true
      return true
    end
    curr_wallet=@user.wallet.all
    sum=0
    for w in curr_wallet
      if w.month==@budgetplaner.month
        sum=sum+w.amount
        
      end
    end
    full_budget=@user.budgetplaner.all
    for fb in full_budget
      if fb.month==@budgetplaner.month
        sum=sum-fb.amount
      end
    end
    if sum>=@budgetplaner.amount
      flag=true
    end
    return flag
  end

  # PATCH/PUT /budgetplaners/1 or /budgetplaners/1.json
  def update
    respond_to do |format|
      if  @budgetplaner.update(budgetplaner_params) && balance_sufficient(@budgetplaner)
        format.html { redirect_to budgetplaner_url(@budgetplaner), notice: "Budgetplaner was successfully updated." }
        
      else
        flash.notice="Insuffiient wallet balance for this month"
        
        format.html { render :edit, status: :unprocessable_entity }
        
      end
    end
  end

  # DELETE /budgetplaners/1 or /budgetplaners/1.json
  def destroy
    @budgetplaner.destroy

    respond_to do |format|
      format.html { redirect_to budgetplaners_url, notice: "Budgetplaner was successfully destroyed." }
      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budgetplaner
      @budgetplaner = Budgetplaner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def budgetplaner_params
      params.require(:budgetplaner).permit(:category, :subcategory, :amount, :notes, :month,:user_id)
    end
end

app/helpers/budgetplaners_helper.rb
module BudgetplanersHelper
end

app/views/budgetplaners/_budgetplaner.html.erb
<div id="<%= dom_id budgetplaner %>">
  <p>
    <strong>Category:</strong>
    <%= budgetplaner.category %>
  </p>

  <p>
    <strong>Subcategory:</strong>
    <%= budgetplaner.subcategory %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= budgetplaner.amount %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= budgetplaner.notes %>
  </p>

  <p>
    <strong>Month:</strong>
    <%= budgetplaner.month %>
  </p>

</div>

app/views/budgetplaners/_form.html.erb
<%= form_with(model: budgetplaner) do |form| %>
  <% if budgetplaner.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(budgetplaner.errors.count, "error") %> prohibited this budgetplaner from being saved:</h2>

      <ul>
        <% budgetplaner.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category, style: "display: block" %>
    
    
    <select id=category,name =budgetplaner[category]>
          <% for c in Category.all%>
          <option > <%=c.cgory%> </option>
          
          <%end%>
  </select>
    
   
  </div>

  <div>
    <%= form.label :subcategory, style: "display: block" %>
    <select id=category,name =budgetplaner[subcategory]>
    <% for c in Category.all%>
    <option > <%=c.scgory%> </option>
    
    <%end%>
</select>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.text_field :notes %>
  </div>

  <div>
    <%= form.label :month, style: "display: block" %>
    <%= form.text_field :month %>
  </div>
  <div>
  <%if current_user.is_admin==true%>
    <%= form.number_field :user_id%>     
    
  <%else%>
    <%= form.number_field :user_id ,value: current_user.id, type: :hidden%>
      
  <% end %>  
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/budgetplaners/edit.html.erb
<p style="color: red"><%= notice %></p>
<h1>Editing budgetplaner</h1>

<%= render "form", budgetplaner: @budgetplaner %>

<br>

<div>
  <%= link_to "Show this budgetplaner", @budgetplaner %> |
  <%= link_to "Back to budgetplaners", budgetplaners_path %>
</div>

app/views/budgetplaners/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Budgetplaners</h1>

<div id="budgetplaners">
  
    <% @budgetplaners.each do |budgetplaner| %>
      <%= render budgetplaner %>
      <p>
      <%= link_to "Show this budgetplaner", budgetplaner %>
      </p>
    <% end %>
  

</div>

<%= link_to "New budgetplaner", new_budgetplaner_path %>
<%= link_to "User HomePage", user_path %>

app/views/budgetplaners/new.html.erb
<p style="color: red"><%= notice %></p>
<h1>New budgetplaner</h1>

<%= render "form", budgetplaner: @budgetplaner %>

<br>

<div>
  <%= link_to "Back to budgetplaners", budgetplaners_path %>
</div>

app/views/budgetplaners/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @budgetplaner %>

<div>
  <%= link_to "Edit this budgetplaner", edit_budgetplaner_path(@budgetplaner) %> |
  <%= link_to "Back to budgetplaners", budgetplaners_path %>

  <%= button_to "Destroy this budgetplaner", @budgetplaner, method: :delete %>
</div>